language: objective-c
os: osx
osx_image: xcode9.3
cache: cocoapods
podfile: Example/Podfile

env:
  global:
    - WORKSPACE=Example/QuickLayout.xcworkspace
    - SCHEME=DemoApp
    - TEST_SDK=iphonesimulator
    - TEST_DEST="platform=iOS Simulator,OS=11.3,name=iPhone 8"

script:
- set -o pipefail
- xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$TEST_SDK" -destination "$TEST_DEST" -configuration Debug | xcpretty
- bash <(curl -s https://codecov.io/bash)
