language: objective-c
osx_image: xcode9.3
cache: cocoapods
podfile: Example/Podfile

env:
  global:
    - WORKSPACE=Example/QuickLayout.xcworkspace
    - SCHEME=QuickLayoutiOSDemo
    - TEST_SDK=iphonesimulator

# travis cache isn't kept between builds
before_install:
  - cd Example
  - pod deintegrate
  - cd ..
  - pod cache clean --all
  - pod repo update

script:
- set -o pipefail
- brew upgrade carthage
- xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' -configuration Debug | xcpretty
- brew upgrade swiftlint
- swiftlint
- bash <(curl -s https://codecov.io/bash) -J 'QuickLayout'
